export type RockType = {
  id: "igneous" | "sedimentary" | "metamorphic";
  name: string;
  signatureColor: string;
  formation: string;
  detail: string;
  examples: { name: string; description: string }[];
  characteristics: string[];
  modal: {
    title: string;
    overview: string;
    svgLabel: string;
  };
};

export const rockTypes: RockType[] = [
  {
    id: "igneous",
    name: "Igneous",
    signatureColor: "magma",
    formation:
      "Igneous rocks crystallize from molten magma or lava. Slow cooling underground creates coarse grains, while rapid cooling at the surface yields fine-grained or glassy textures.",
    detail:
      "At mid-ocean ridges, subduction arcs, and mantle plumes, melt generation and cooling form Earths primary crustal building blocks.",
    examples: [
      { name: "Granite", description: "Intrusive; large feldspar and quartz crystals." },
      { name: "Gabbro", description: "Dense intrusive mafic rock from slow cooling." },
      { name: "Basalt", description: "Extrusive lava rock; dominant oceanic crust." },
      { name: "Obsidian", description: "Volcanic glass quenched too quickly to crystallize." },
    ],
    characteristics: [
      "Intrusive vs extrusive textures reflect cooling rate",
      "Crystal size increases with slower cooling",
      "Can range from silica-rich felsic to silica-poor mafic",
    ],
    modal: {
      title: "Igneous Rock Formation",
      overview:
        "Melt generated by decompression, volatiles, or heat transfer rises and cools. Intrusive systems may cool over millions of years; extrusive lavas can solidify in hours to days.",
      svgLabel: "Crystal lattice and cooling fronts",
    },
  },
  {
    id: "sedimentary",
    name: "Sedimentary",
    signatureColor: "sediment",
    formation:
      "Sedimentary rocks form when weathered fragments, precipitated minerals, or organic material are buried, compacted, and cemented into solid strata.",
    detail:
      "Rivers, deltas, shelves, and basins archive environmental change layer by layer through deposition and lithification.",
    examples: [
      { name: "Sandstone", description: "Clastic rock of cemented sand grains." },
      { name: "Shale", description: "Fine mud-rich layers compacted into thin sheets." },
      { name: "Limestone", description: "Chemical or biogenic carbonate accumulation." },
      { name: "Conglomerate", description: "Rounded gravel clasts in a finer matrix." },
    ],
    characteristics: [
      "Commonly layered with bedding planes",
      "May preserve fossils and paleoenvironment clues",
      "Porosity and cement type control fluid flow",
    ],
    modal: {
      title: "Sedimentary Rock Formation",
      overview:
        "Physical and chemical weathering produce sediment. Transport sorts grains by energy; burial increases pressure and pore-fluid chemistry drives cementation.",
      svgLabel: "Layered strata and grain packing",
    },
  },
  {
    id: "metamorphic",
    name: "Metamorphic",
    signatureColor: "slate-blue",
    formation:
      "Metamorphic rocks form when existing rocks recrystallize under elevated heat, pressure, and fluids without fully melting, often during tectonic burial and collision.",
    detail:
      "Typical metamorphism begins near 200°C and around 10 km depth, increasing through regional mountain-building events.",
    examples: [
      { name: "Slate", description: "Low-grade foliated rock from shale." },
      { name: "Schist", description: "Medium-grade foliation with visible micas." },
      { name: "Gneiss", description: "High-grade compositional banding." },
      { name: "Quartzite", description: "Non-foliated metamorphosed sandstone." },
    ],
    characteristics: [
      "Minerals align under directed stress (foliation)",
      "Grade increases with temperature and pressure",
      "Chemical fluids can trigger metasomatic reactions",
    ],
    modal: {
      title: "Metamorphic Transformation",
      overview:
        "As crust is thickened or subducted, minerals re-equilibrate. New mineral assemblages record pressure-temperature-time paths through tectonic settings.",
      svgLabel: "Pressure gradient and foliation bands",
    },
  },
];
